---
abstract: 'Unload a class'
author:
  - 'Dagfinn Ilmari Mannsåker <ilmari@ilmari.org>;'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101151'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Unload
recommends: {}
requires:
  Class::Inspector: 0
resources:
  repository: http://github.com/ilmari/class-unload
version: 0.06
