---
abstract: 'Unload a class'
author:
  - 'Dagfinn Ilmari Mannsåker <ilmari@ilmari.org>;'
build_requires:
  Test::More: 0
  base: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Unload
requires:
  Class::Inspector: 0
  strict: 0
  warnings: 0
version: 0.08
